# Generated by Django 3.1.6 on 2021-02-11 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='N/A', max_length=30)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='N/A', max_length=200)),
                ('direccion', models.CharField(default='N/A', max_length=500)),
                ('telefono', models.CharField(default='N/A', max_length=10)),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
            },
        ),
        migrations.CreateModel(
            name='EstadoActivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='N/A', max_length=30)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='MarcaActivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='N/A', max_length=30)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='ModeloActivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='N/A', max_length=30)),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='TipoBienActivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='N/A', max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo de Bien',
                'verbose_name_plural': 'Tipos de Bienes',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='N/A', max_length=200)),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='N/A', max_length=10)),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=50)),
                ('observaciones', models.TextField()),
                ('mantenimiento', models.BooleanField()),
                ('ciudad', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activos.ciudad')),
                ('delegado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('establecimiento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activos.establecimiento')),
                ('estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activos.estadoactivo')),
                ('marca', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activos.marcaactivo')),
                ('modelo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activos.modeloactivo')),
                ('tipo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activos.tipobienactivo')),
                ('ubicacion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activos.ubicacion')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
            },
        ),
    ]
