# Generated by Django 3.1.6 on 2021-09-13 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activo',
            old_name='tipo',
            new_name='categoria',
        ),
        migrations.AddField(
            model_name='activo',
            name='n_serie',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activo',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activo',
            name='codigo',
            field=models.CharField(default='N/A', max_length=25),
        ),
        migrations.AlterField(
            model_name='activo',
            name='delegado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
