# Generated by Django 3.1.6 on 2021-09-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_auto_20210913_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='color',
            field=models.CharField(default='N/A', max_length=80),
        ),
    ]
